#workspace = { members = ["crates/transport"] }

[package]
name = "nevy"
version = "0.0.1"
edition = "2021"
categories = ["network-programming", "game-development"]
description = "Simple, expressive networking for your bevy games"
keywords = ["netcode", "networking", "bevy"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/DrewRidley/nevy"
documentation = "https://docs.rs/nevy"

[features]
rkyv = []
serde = []
default = []


[dependencies]
anyhow = "1.0.86"
bevy = "0.13"
bevy_async_task = "0.1.1"
bevycheck = "0.5.2"
bincode = "1.3.3"
dashmap = "5.5.3"
quinn = { version = "0.11.0", features = ["ring", "runtime-smol"] }
rustls = "0.23.7"
rustls-native-certs = "0.7.0"
rustls-pemfile = "2.1.2"
rustls-platform-verifier = "0.3.1"
serde = { version = "1.0.202", features = ["derive"] }
slotmap = "1.0.7"
smol = "2.0.0"
tokio = { version = "1.37.0", features = ["rt", "sync"] }
unique-type-id = "1.3.0"
url = "2.5.0"

web-transport = { git = "https://github.com/kixelated/web-transport-rs.git" }
web-transport-quinn = { git = "https://github.com/kixelated/web-transport-rs.git" }
web-transport-wasm = { git = "https://github.com/kixelated/web-transport-rs.git" }
