workspace = { members = ["crates/transport"] }
[package]
name = "nevy"
version = "0.0.1"
edition = "2021"
categories = ["network-programming", "game-development"]
description = "Simple, expressive networking for your bevy games"
keywords = ["netcode", "networking", "bevy"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/DrewRidley/nevy"
documentation = "https://docs.rs/nevy"

[features]
rkyv = []
serde = []
default = ["serde"]


[dependencies]
bevy = "0.12"
bincode = "1.3.3"
dipa = { version = "0.1.1", features = ["derive"] }
indexmap = "2.1.0"
memoize = "0.4.2"
num-traits = "0.2.17"
rkyv = "0.7.43"
serde = "1.0.193"
smallvec = "1.12.0"
