[package]
name = "nevy"
version = "0.0.1"
edition = "2021"
categories = ["network-programming", "game-development"]
description = "Simple, expressive networking for your bevy games"
keywords = ["netcode", "networking", "bevy"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/DrewRidley/nevy"
documentation = "https://docs.rs/nevy"

[dependencies]
bevy = "0.12"
bincode = "1.3.3"
dipa = { version = "0.1.1", features = ["derive"] }
serde = "1.0.193"
