[package]
name = "nevy_messaging"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_interface.path = "../bevy_interface"
bevy.workspace = true
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
